version: "3.9"

services:
  pilipili_backend:
    image: hsuyelin/pilipili_backend:latest
    container_name: ${CONTAINER_NAME:-pilipili_backend}
    environment:
      - UID=0
      - GID=0
      - GIDLIST=0
      - TZ=Asia/Shanghai
    volumes:
      - ./config/config.yaml:/app/config.yaml:ro
      - /mnt/anime:/mnt/anime:ro # Map storage to the container based on actual requirements. / 按照实际情况映射存储到容器
    restart: unless-stopped
    privileged: true
    network_mode: host